### ISSUE TITLE
createComponent helper function

### ISSUE THREAD

**Issue by calebmer** [acdlite/recompose#135]
Often I find myself using `compose` and `pure` to create React components. I think a better pattern would to have a single `createComponent` helper.

```js
export default createComponent(
  getContext({
    store: PropTypes.object.isRequired,
  }),
  setPropTypes({
    name: PropTypes.string.isRequired,
  }),
  ({ name }) => (
    <div>Hello {name}!</div>
  )
)
```

The `createComponent` helper would act like `compose` except the last argument is expected to be the stateless function. `createComponent` would also automatically add the `pure` decorator.

**Comment by istarkov** [comment]
`pure` will break any application which does not use immutable data, (or immutable data behavior).
Because of this, React does not use this optimization by default. 
So the recompose must have the same behavior as React itself.

createComponent name does not say much about any optimization like pure, so it will be not a good idea to create such hoc - as it will confusing users.
You could  easily create and use this HOC in your own project.

**Comment by calebmer** [comment]
How about two functions `createComponent` and `createPureComponent`? This is a helper I've been using in my projects for a while now, so I figured it might be useful to try adding it to `recompose`. I'll submit a PR so we can talk about actual specs.

**Comment by acdlite** [comment]
Follow in https://github.com/acdlite/recompose/issues/136
