### ISSUE TITLE
How about a withPropTypes?

### ISSUE THREAD

**Issue by low-ghost** [acdlite/recompose#20]
great library! So, I had been doing prop types, at least with stateless functions, like so:

```js
const component1 = (props) => <div {...props} />;

component1.propTypes = { ... };

export default component1;
```

Which looks ugly. Maybe it's even too simple for this lib, but a withPropTypes could look like

```js
const withPropTypes = curry((propTypes, component) => component.propTypes = propTypes);
```

Would still support non-stateless components while fitting nicely in the final compose.

**Comment by low-ghost** [comment]
Or actually... you'd have to create a new component to avoid mutating state and actually use the return value, right? Like:

```js
const withPropTypes = curry((propTypes, BaseComponent) => React.createClass({
     propTypes,
     render() {
          return <BaseComponent {...this.props } />;
     }}));
```

**Comment by acdlite** [comment]
Good idea. In 0.6.0 I've added a set of static helpers, including one called [`setPropTypes()`](https://github.com/acdlite/recompose/blob/master/docs/API.md#setproptypes), which works essentially the same as the version in your original comment.

Since `propTypes` are only useful during development, I don't think it makes sense to wrap the base component in a new component, so this actually mutates the base component.

Thanks for the suggestion!

**Comment by low-ghost** [comment]
Awesome, the implementation looks great. Thanks!
