### ISSUE TITLE
Using getContext as a decorator breaks static variables

### ISSUE THREAD

**Issue by rossipedia** [acdlite/recompose#216]
It seems as though using the `@getContext()` form doesn't propagate static variables to the resulting component type.

``` javascript
const { Component, PropTypes } = React;
const { render } = ReactDOM;
const { getContext } = Recompose;

// Uncomment this to show breaking behavior
// @getContext()
class App extends Component {
  static foo = "Hello";
  render() {
    return (
      <div>{App.foo}</div>
    );
  }
}

// This still works though
// App = getContext()(App); 

render(
  <App />,
  document.getElementById('app')
);

```

Expected output is:

`<div>Hello</div>`, but instead output is `<div></div>`

JSBIN showing the behavior:

https://jsbin.com/buqeqac/edit?html,js,console,output

I'm not sure if this affects the decorator form of other helpers, I only use `@getContext()` so far. I realize decorators aren't a standard thing yet, but your docs say they can be used as such.

**Comment by jcemer** [comment]
The `getContext()` returns a new function. In fact, it shouldn't work in both snippets.

The snippet with `App = getContext()(App);` just works because of the way that Babel handles class transpilation.

I think that a function should only by used as decorator when it returns the given target. Maybe is better to remove the recommendation to use recompose functions as decorators. What do you think @acdlite?
