### ISSUE TITLE
shouldUpdate doesn't update when context is updated

### ISSUE THREAD

**Issue by rundmt** [acdlite/recompose#284]
Is there a current way to use `shouldUpdate` and control for `context`? Currently `shouldUpdate` only tests for `this.props` and `nextProps`, but if I want to update a component on a `context` change I don't see a way to account for that.

Currently:
```
const shouldUpdate = test => BaseComponent => {
  const factory = createEagerFactory(BaseComponent)
  return class extends Component {
    shouldComponentUpdate(nextProps) {
      return test(this.props, nextProps)
    }

    render() {
      return factory(this.props)
    }
  }
}
```

If not then maybe we could make a new helper component like this:
```
const shouldUpdateWithContext = test => childContextTypes => BaseComponent => {
  const factory = createEagerFactory(BaseComponent)
  class ShouldUpdateWithContext extends Component {

    shouldComponentUpdate(nextProps, nextState, nextContext) {
      return test(this.props, nextProps, this.context, nextContext)
    }

    render() {
      return factory(this.props)
    }

    ShouldUpdateWithContext. childContextTypes = childContextTypes

    return ShouldUpdateWithContext
  }
}
```

We probably wouldn't use `nextState` for anything, but something needs to be there as `nextContext` is the third argument.

Alternatively we could add this functionality to `shouldUpdate`.

Thoughts?

**Comment by istarkov** [comment]
Hi thank you, 
I see the problem in your idea. The problem is that context will not be available at  component level without setting it explicitly https://facebook.github.io/react/docs/context.html#referencing-context-in-lifecycle-methods

So just `shouldUpdateWithContext` enhancer is not enough, you need to explicitly set for your functional component `contextTypes` otherwise `context` will not be available as functional component argument. 
And code duplication is not the only problem here, the other problem that `context` will make functional component not referentially transparent https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isReferentiallyTransparentFunctionComponent.js#L7 so some optimizations will not work.

So IMO the better way is to use `getContext` enhancer before original `shouldUpdate`

**Comment by rundmt** [comment]
I see. Thanks for the tip. I'll give it a shot.
