### ISSUE TITLE
[Discussion/Documentation] Why is use of `lifeCycle()` considered an escape hatch?

### ISSUE THREAD

**Issue by sdtsui** [acdlite/recompose#285]
Not sure if this is a dumb question -- apologies in advance if so. It's a beginner question, but unrelated to #264.

Say I want to add an ajax call to my widget's `componentWillMount`. If this use case + a propTypes declaration is all I need, why not implement with only `recompose` functions and a stateless component? What's the idiomatic way to write a component with only these two requirements (propTypes, componentWillMount)? 

See title: why is use of `lifecycle`an escape hatch?  Should I default to using a class here?  Source is the [docs](https://github.com/acdlite/recompose/blob/master/docs/API.md#lifecycle), and remembering part of @acdlite 's ReactEurope [talk](https://youtu.be/zD_judE-bXk?t=17m15s) (timestamped) where how he observed "excessive" overuse of HoCs. **More generally, what are things I should always do in classes? What is the set of things I can do in HoCs, and how can I learn more about the subset of cases where I _can_ do something with a HoC but should use a class instead?**

My team is new to `recompose`, uses classes for almost everything, and is very open to new ideas. We're starting a new, fairly large project. I'd be extremely appreciative of some context to help inform our standards/conventions. Genuinely interested and hoping to learn more about how to use this library. Happy to summarize add a PR to the docs if this discussion merits it.

Thanks!

**Comment by istarkov** [comment]
Hi!
1) `componentWillMount` is not a good place for ajax calls, and I'm talking not even about server rendering, but [here](https://github.com/facebook/react/issues/7671) is a good discussion about.
2) IMO No idiomatic way how you will write your components, it depends on your code style, on component requirements, usage etc.
3) `lifecycle` please [read](https://github.com/acdlite/recompose/pull/280#issuecomment-263378813) IMO this enhancer not needed at all.
4) `what are things I should always do in classes` IMO every time you need `refs`, window like event processing ('resize' etc), or aggressive code optimizations you should use classes. For some controls you can publish it's not bad to avoid external dependencies.

Just be easy, think less about idiomatic ways and other things, try different solution, there is no need to be on edge case and use only functional components and recompose.

My team use recompose because it makes code linear and more readable, it took some time before every team member started to love this library ;-)

Good day!

**Comment by wuct** [comment]
I am going to close this issue because it's no longer active. Please feel free to reopen it.
