### ISSUE TITLE
[Question] WithReducer: justification of async reducer function call

### ISSUE THREAD

**Issue by komlev** [acdlite/recompose#301]
I'm using withReducer HOC and noticed this behaviour. Calling this on click handler for example:

```js
import React from 'react'
import { withReducer } from 'recompose'
import { compose } from 'ramda'

export default compose(
  withReducer('state', 'dispatch', (state, { value }) => {
    console.log(value)
    return { ...state, value }
  }, { value: 'zero' })
)((props) => {
  const { dispatch, state } = props,
    onClick = () => {
      console.log('Hello')
      dispatch({ value: 'one' })
      dispatch({ value: 'two' })
      dispatch({ value: 'three' })
      console.log('World')
    }
  return (
    <div>
      <div>{state.value}</div>
      <button onClick={onClick}>Click me</button>
    </div>
  )
})
```
It will produce

> Hello
> World
> one
> two
> three

This means that reduce function is called asynchronously. What is justification for calling it async rather than applying changes to store right away?

---
Question on stackoverflow: http://stackoverflow.com/questions/41521459/recompose-withreducer-justification-of-async-reducer-function-call

**Comment by wuct** [comment]
Thanks for your question. I've answered it on SO, but I think this question is worth to discuss here so I am going to copy my answer to here.

My answer copy from SO:

The reducer is called asynchronously because we can only use `setState` to update the tree and `setState` is asynchronous.

If we call the reducer synchronously, we will need to save the new state somewhere, then call `setState` and get the new state asynchronously from where we save it. In the end, your tree still get updated asynchronously.

This is why recompose's `withReducer()` is slightly different from redux. You can think of that `withReducer` is a simplified version of redux + react-redux's `connect()`.

**Comment by komlev** [comment]
@wuct Yep. I see now. Thanks for the clarification! I guess I need to write custom HOC to handle sync use cases.
