### ISSUE TITLE
Inferno.js support

### ISSUE THREAD

**Issue by ugros** [acdlite/recompose#317]
Just a quick question/suggestion.

Does recompose work with Inferno.js?
https://github.com/infernojs/inferno

And If not, how hard would it be to add support for it?

Thanks!

**Comment by istarkov** [comment]
Why not to check it by yourself?

**Comment by wuct** [comment]
Close this issue because it seems like there is nothing we can do here.

**Comment by gevgeny** [comment]
Did somebody check ?

**Comment by rikkertkoppes** [comment]
It is kinda hard to check, since it would require knowledge on how recompose works internally, because just trying will likely miss problem areas.

That said, this suggests its specifically tailored to react in at least one spot: https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isClassComponent.js#L5

	const isClassComponent = Component =>
	  Boolean(
	    Component &&
	      Component.prototype &&
	      typeof Component.prototype.isReactComponent === 'object'
	  )

So I'd like to rephrase the question to: "are there any (other) react specific implementation details in recompose?"

**Comment by istarkov** [comment]
It depends on what this mean "React specific"
for example inferno compat supports `isReactComponent` so is it react specific?

**Comment by andreyluiz** [comment]
I think it is not that simple.

Recompose HOCs uses `createFactory` in some cases. `branch` is an example. This may work with ìnferno-compat`, but not with pure inferno.
