### ISSUE TITLE
How do you create a reasonable function signature?

### ISSUE THREAD

**Issue by GollyJer** [acdlite/recompose#375]
How do you guys create an understandable/reasonable function signature?
Ignoring typings for now, I'm having trouble simply coming up with a way, without `//code comments` to provide a quickly readable signature.

**Example**
The following ThemedIcon component allows the developer to set the `color` directly, or pass in a `colorBehindIcon` (which colors the icon based on an acceptable color list), or pass no color information and simply use the current theme color.

Without a lot of reading it's difficult to understand that you can pass in `color, colorBehindIcon, null`.
**Is there a best practice around signatures like this?**

Thanks!

```
const ThemedIcon = ({ color, ...remainingProps }) => <Icon color={color} {...remainingProps} />;

const enhance = compose(
  withProps(({ color, colorBehindIcon }) => {
    let iconColor = StyleSheet.flatten(styles.enabledIcon).color;
    if (color) {
      iconColor = color;
    } else if (colorBehindIcon) {
      iconColor = mostReadableColor(colorBehindIcon, theme.color.acceptableTextColors);
    }

    return {
      color: iconColor,
    };
  }),
);

export default enhance(ThemedIcon);
```

**Comment by everdimension** [comment]
Am I correct in understanding that the resulting component will be use in one of these ways? —

* `<ThemedIcon />`
* `<ThemedIcon color="magenta" />`
* `<ThemedIcon behindColor="magenta />`

`PropTypes` are what you need.

First, you don't really need `compose` because in your example you're not composing anything. `enhance` could be rewritten:

```javascript
const enhance = withProps(/* ...rest of code... */);
```

Second, you don't really need `recompose` for this. Since a child of you enhanced component will always be `ThemedIcon`, it would be much more straightforward to create a parent component like this:

```javascript
const propTypes = {
  color: PropTypes.string,
  behindColor: PropTypes.string,
};

const defaultProps = {
  // this color will be used if no "color" prop is passed
  color: StyleSheet.flatten(styles.enabledIcon).color,
};

const EnhancedThemedIcon = ({ color, colorBehindIcon, ...rest }) => {
  let iconColor = color;
  if (colorBehindIcon) {
    iconColor = mostReadableColor(colorBehindIcon, theme.color.acceptableTextColors);
  }
  return (
    <ThemedIcon {...rest} color={iconColor} />
  );
};

EnhancedThemedIcon.propTypes = propTypes;
EnhancedThemedIcon.defaultProps = defaultProps;
```


...But if you really wish to use `recompose` anyway there's a handy [`setPropTypes`](https://github.com/acdlite/recompose/blob/master/docs/API.md#setproptypes) helper:

```javascript
const enhance = compose(
  setPropTypes({
      color: PropTypes.string,
      behindColor: PropTypes.string,
  }),
  withProps(/* ...rest of code... */),
);
```

---

> Without a lot of reading it's difficult to understand that you can pass in color, colorBehindIcon, null.

So using `PropTypes` is a first step towards easier to understand components.

But also that's what static typing is for. You might be interested in cheking out [typescript](https://www.typescriptlang.org/index.html) or [flow](https://flow.org/) — these projects add static typing to javascript.

**Comment by GollyJer** [comment]
Thanks a TON for the response @everdimension !
Sorry for the late reply.  I was away for a while.

You are correct in your assumption of how the component is used.  Your information about types is greatly appreciated.  After a little research it seems TypeScript is pretty far ahead of Flow and would probably be the choice if I go that route.

I realize *recompose* isn't really necessary but I am trying to find a consistent way to structure my components and am doing the following...
```
const MyComponentPresentation = (props) =>
  <Text>Only presentation is found here</Text>

const MyComponent = compose(
  withState.... withEvents.... withProps.... etc...
  (/* ...functionality found here... */),
)(MyComponentPresentation);

default export MyComponent
```

This has made it easy to jump back into components and get going pretty quickly when not looking at them a while.

Am I crazy to do it this way?
