### ISSUE TITLE
Question about recompose/branch

### ISSUE THREAD

**Issue by nehaleem** [acdlite/recompose#460]
Hello there,
i'm struggling a bit with different HOCs that are using input as rendered element. I want to use uncontrolled input, where values is stored inside DOM, but i want to keep this value after reupdate with recompose/branch. 

I'm attaching jsfiddle, where my problem is described. There are two HOC. Each render different input border depending on value inside input. When its "red", border should be red. Thing is, when branch render second HOC (blue), it will discard last input value.

Is there any way (without using controller input with value={}) ?

https://jsfiddle.net/m2wxk0wa/3/

OR:

```js
class Input extends React.PureComponent {
        render() {
            return <input
                {...this.props}
                type="text"
             />;
        }
      }
      
      const redInput = () => (Component) => {      
        class RedInput extends React.Component {
           render () {
              return (
                <div><Component className="red" {...this.props} /></div>
              );
           }
        }
        
        return RedInput;
      }
      
       const blueInput = () => (Component) => {      
        class BlueInput extends React.Component {
           render () {
              return (
                <div><Component className="blue" {...this.props} /></div>
              );
           }
        }
        
        return BlueInput;
      }


const colloredInput = Recompose.branch(({ isRed }) => isRed, redInput(), blueInput());
const FormColloredInput = colloredInput(Input);

class App extends React.Component {
    constructor (props) {
       super(props);
       this.state = {
         isRed: false,
       };
    }
    
    render () {
      return (
        <div>
          <FormColloredInput isRed={this.state.isRed} onChange={(event) => this._onInputChange(event)} />
          {this.state.isRed ? 'isRed' : 'isBlue'}
        </div>
      );
    }

    _onInputChange (event) {
       this.setState({ 
         isRed: event.target.value === 'red',
       });
    }
}


      ReactDOM.render(<App />, document.getElementById('container'));
```

**Comment by faergeek** [comment]
The problem with your solution is that you've got two completely separate components (even though they look almost the same). It means react will unmount first component, and mount second when changing from red to blue. The reason is that (simplified) react makes simple comparison to determine if that's the same component (it checks something like `BlueInput` === `RedInput`). And that check fails, so remounting happens. That's why you lose state.

I mean `branch` is just not what you need in this case. Passing simple prop instead of different component will work perfectly. If you have some more complex usecase, please describe it.

**Comment by wuct** [comment]
I'm going to close this issue and please feel free to reopen it if there is any further question.
