### ISSUE TITLE
Issue with withState, documentation and (quite possibly my) assumptions...

### ISSUE THREAD

**Issue by Panoplos** [acdlite/recompose#461]
I am going to admit that I both love and hate this library. I love the philosophy behind it and love the ease of creating functional components, but I have real issues with the documentation, especially when it comes to using recompose with local state vs. a redux store.

For instance, I have a generic `withModal` HOC that looks like:

```es6
export default compose(
  setPropTypes({
    modal: PropTypes.func
  }),
  withProps(
    props => ({ modal: hashToModal(props.location.hash) })
  )
)
```

And I have a `Modal` container like this:

```es6
export default (hash) => {
  
  const mapStateToProps = (state: Object) => ({
    parentLocation: state.modal.parentLocation
  })

  const mapDispatchToProps = (dispatch: Dispatch) => ({
    closeModal(parentLocation: string) {
      dispatch(closeModal(parentLocation))
    }
  })

  return [
    connect(mapStateToProps, mapDispatchToProps),
    lifecycle({
      componentDidMount() {
        $(hash)
          .modal({
            detachable: false,
            onHidden: () => {
              this.props.closeModal(this.props.parentLocation)
              return true
            }
          })
          .modal('show')
      },
      componentWillUnmount() {
        $(hash).modal('hide')
      }
    })
  ]
}
```

Which is used like:

```es6
const LoginModal = ({location, closeModal}) =>
  <div>
    A lot of markup....
  <button onClick={() => closeModal(location)}>Cancel</button>
  </div>

export default compose(
  ...enhanceModal('#login'),
  ...otherHocs
)(LoginModal)
```

Now, this works OK, but I am running into a few quirks around history management -- namely, when the user presses back in the browser, `closeModal(...)` is pushing an extraneous path.

So, I began thinking that Redux was not at all necessary in this scenario, as I am using `react-router-redux`, so I would get state change tracking for free if I just use local state in the modal composition.

I then ventured something along these lines in the enhancer:

```es6
export default (hash) => {
  return [
    withState(
      'noBack', 'setNoBack', false
    ),
    lifecycle({
      componentDidMount() {
        $(hash)
          .modal({
            detachable: false,
            onHidden: () => {
              if (!this.props.noBack) {
                this.props.history.goBack()
              }
              return true
            }
          })
          .modal('show')
      },
      componentWillUnmount() {
        this.props.setNoBack(true)
        $(hash).modal('hide')
      }
    })
  ]
}
```

Now, the issue I am having is that even after calling `setNoBack(true)`, `this.props.noBack` is still false on the `onHidden` event. You can see it here:

![withstate issue](https://user-images.githubusercontent.com/2549985/28867623-a66f189c-77b1-11e7-92e9-678d4e6ddb97.png)

Here are some assumptions I have:

1. Recompose `withState` simply creates 2 props. One with the state and one to manipulate the state.
2. When I call the state manipulator, the prop represented in the `withState` call should be manipulated.

Am I wrong in assumption 2?

Additional question (as a new user):

1. Are `pure` optimizations inherited by children, or do I need to declare this on a per-component basis? Are there runtime checks in development mode that flag violations of purity when this is used?

**Comment by joedski** [comment]
`withState` itself uses React state and `setState` internally to trigger rerenders on changes to that state.  This means a few things for you here:
- `$(hash).modal('hide')` is called while `noBack` is `false`, as you observed.
- `onHidden` is presumably triggered in the same call stack, since triggering it later could lead to unpredictable behavior, and therefore still sees `this.props.noBack` as `false`, as you also observed.
- Calling `this.props.setNoBack(true)` will have no effect because the component is being unmounted, so it doesn't have a chance to rerender with the updated state.

Not sure I can add much without knowing more about your architecture, but my first thought is that in the `onHidden` callback you could check the current `stateBeforeTransition` to see if the last action was a `POP` (that is, the user hit the back button) and act accordingly. (or don't act, as it were.) but I'm not sure if you can get the current redux state in an unmounting component without resorting to just straight up calling `getState`.

As to `pure`, it applies only to the component it's applied to.  It shouldn't be necessary to use it everywhere since changes in props at the top of a (sub)tree will most likely require rerendering many children anyway.  How granular you get with it is of course up to you.

**Comment by Panoplos** [comment]
@joedski Thanks for the feedback! You helped me understand something important, namely that props will not be updated on the component to match the redux store (which I confirmed was actually being changed) before getting into `componentWillUnmount()`. I assumed that this would have happened.

Your suggestion to check for `POP` would have worked, but I moved along to a cleaner solution (implemented my own base modal instead of relying on semantic-ui's, which manipulates the DOM, anyway.)

Again, thanks!
