### ISSUE TITLE
[Question] - what will happen to lifecycle()?

### ISSUE THREAD

**Issue by pr1ntr** [acdlite/recompose#521]
I am not sure where to get the answer to this. I use lifecycle quite a bit and am wondering what to do when it is removed?

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/issues/510#issuecomment-328737373

**Comment by j** [comment]
@istarkov a link to a comment saying to search the forums?  Can you please just write an issue about why it's being deprecated and answer the question that way?  I search "lifecycle deprecate" and it's a pain to find.. I can't find what's going on?

**Comment by istarkov** [comment]
Isn't it a pain for me write the same things? Do you think I remember the exact place, I also need to search so why me not you? ;-)

**Comment by j** [comment]
@istarkov I'm still trying to search for it.  Can't find anything.  Nothing.  Zilch.  All I see are links to #510 which says to search for it and searching for it brings nothing.  I mean, there'd be a lot less confusion with people if you actually answered or had the answer in a clear location and referred people to that.  People are using your library and trusting in your library.  Without a clear answer from the author himself, you lose that trust.

**Comment by j** [comment]
Perhaps this is the answer. #280

**Comment by mcky** [comment]
Hey @istarkov, I also had a look through the code and issues but couldn't find anything that really cleared up the depreciation reason. I'm happy to create a PR to the docs with it if you can point me in the right direction?

**Comment by timkindberg** [comment]
It's discussed in various places:
- #500
- https://github.com/acdlite/recompose/issues/502#issuecomment-326417143
- https://github.com/acdlite/recompose/issues/502#issuecomment-326417143
- https://github.com/acdlite/recompose/pull/310#issuecomment-276028392

The main reason for deprecation seems to be claims that:
- It is a large source of bugs for the maintainer
- It has a different api than the other HOCs. For example, how you have to access props via `this.props` rather than having them passed in as a function param. 

I personally do not think it should be deprecated.

**Comment by mcky** [comment]
Thanks, that makes a lot of sense, I think #500 and the usage of `this` was the missing piece in understanding

**Comment by machineghost** [comment]
I'm curios, one of the linked issues references https://github.com/deepsweet/hocs/tree/master/packages/with-lifecycle, which seems to answer all of the concerns about `lifecycle` here (it passes props in, doesn't reference a class instance, etc.).  Instead of eliminating `lifecycle` completely why not just replace it with `withLifecycle`?
