### ISSUE TITLE
Strange behaviour in flow types when using mapProps

### ISSUE THREAD

**Issue by eskimoblood** [acdlite/recompose#561]
I try to use the flow type definitions from recompose but there are some strange behaviours when used with `mapProps`.
```
const f = ({ foo }) => ({ bar: foo })
const f1 = ({ bar }) => ({ poo: bar * 2 })

type A = { foo: number }
type B = { bar: number, poo: number, foo: number }
const eI: HOC<A, B> = compose(mapProps(f), withProps(f1))
```
This will end in complaining about type `A` in the last line, but it does not complain about the missing `foo` in the output
```
[flow] property `foo` (Item.js:6:15) Property not found in object type (recompose_v0.24.x.js:94:10)
```

But it complains about the missing `foo` in type `B` in this one:
```
const f = ({ foo }) => ({ bar: foo })
const f1 = ({ bar }) => ({ poo: bar * 2 })

type B = { bar: number, poo: number }
const eI: HOC<*, B> = compose(mapProps(f), withProps(f1))
```
One thing that I dont understand in general is why I have to put in the type of the enhanced prop but can leave the type of the input prop empty. Is it intend to work with only the input type as well?

**Comment by k** [comment]
It should complain about A in the first case because A does not have bar, but the withProps expects it does.

If I'm reading this correctly, it looks like the * in the second example should be inferred to be 
type A2 = { foo: number, bar: number }

I would try swapping the places of the two HOCs in the compose.

**Comment by eskimoblood** [comment]
Ok, than my understanding of what `A` is used for is wrong. I expected to be the type of the incoming prop. With your explanation its unclear for me what its stands for.
Also in the second example why should there be a type that has `foo` and `bar`. There is an object with `foo` coming in with `bar` and `poo`coming out.

**Comment by k** [comment]
I think your understanding of A is correct. It is the Base props (the props of the component that the HOC is called on). The problem is the first applied HOC is your withProps which expects a bar prop, but A does not have bar. Therefore flow should error.

If you use the existential type (*) then it should be inferred by destructure in the arguments of withProps.

I would format these correctly but I'm on my phone ;)

**Comment by eskimoblood** [comment]
But the first HOC is always `mapProps`

**Comment by k** [comment]
But compose(hoc1, hoc2)(component) gets converted to 
Hoc1(hoc2(component)) so hoc2 is applied to the component first

**Comment by eskimoblood** [comment]
Argh, you are right. Needed some time to wrap my head around it.

**Comment by k** [comment]
All good, glad you got it!
