### ISSUE TITLE
onlyUpdateForKeys reverse [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [acdlite/recompose#583]
Would you consider to add an `onlyUpdateForKeys` HOC with opposite logic to NOT update only for given keys?
i.e: `@notUpdateOnlyForKeys(['key1', 'key2']) //update for all props change but key1 and key2`

**Comment by istarkov** [comment]
No, I think every similar hoc, even onlyUpdateForKeys is the road to hell. The only good similar hoc is pure
It caused almost impossible to find errors in a big team made projects. Something is blocking component update, but where and why is hard to find.

**Comment by damianobarbati** [comment]
Should I prefer `@pure` over `@onlyUpdateForKeys`? Does the first allow better debugging about where the render was stopped?

**Comment by istarkov** [comment]
pure will never stop an update if property has changed (I mean immutable change), so pure does not affect at all your execution flow (if it does it means you do something wrong with react)

onlyUpdateForKeys changes execution flow,  and this can cause hard to find and to debug a lot of bugs.

**Comment by istarkov** [comment]
may be execution flow is bad words, output is better.

**Comment by istarkov** [comment]
It was one of my first error with React framework few years ago.
I used similar idea like `onlyUpdateForKeys` checking only data keys, but not the handlers. And all was fine as all handlers I wrote were placed in `this`

My teammates used anonymous functions as a handlers, and all my controls - components I wrote didn't work in my teammates code. Because in such case used outdated handlers. (Components didn't updated if handlers were changed on every render)

**Comment by wuct** [comment]
The other reason that we're not going to accept this request is that we do not tend to increase our API surface and the request is easy to be implemented with [`shouldUpdate()`](https://github.com/acdlite/recompose/blob/master/docs/API.md#shouldupdate).

I'm going to close this issues, and please feel free to reopen it if you have any further thought.
