### ISSUE TITLE
Best practice on many HOC

### ISSUE THREAD

**Issue by Dictory** [acdlite/recompose#591]
Hello! I have a question: what about many HOC\`s? How i need use it: with stateful component or `lifecycle` and etc.?

for example:
```javascript
const enhance = compose(
  defaultProps(listDefaultProps),
  setPropTypes(ListPropTypes),
  mapProps(({ listKey, ...props }) =>
    ({ listKey: props.isAlbums ? ALBUMS_LIST_KEY : listKey, ...props })),
  connect(getPropsNow, toActions, toMerge),
  onlyUpdateForKeys(['listKey', 'store', 'resource', 'exist']),
  lifecycle({
    componentDidMount() {
      this.props.init();
    },
    componentWillReceiveProps(nextProps) {
      const { listKey, exist, init } = nextProps;
      if (this.props.listKey !== listKey && !exist) init();
    },
    componentWillUnmount() {
      const { clear, removeState } = this.props;
      if (clear) removeState();
    },
  }),
  branch(({ exist }) => !exist, renderNothing),
);
```

Any advice? Mistakes in that code?
Thank you.

**Comment by istarkov** [comment]
Can you be more clear in your question? What about many hocs? What? ;-)

**Comment by pokorson** [comment]
@Dictory I think it's better than writing all of this in class component. 

In my projects I'm trying to organize and compose HOC's by features instead of `recompose` methods. So I'm splitting such big structure to group of composed HOC's and giving them more meaningful names, and then I compose them again to apply features to component

**Comment by Dictory** [comment]
@pokorson thank you!
@istarkov what i mean:
Is it right use many components to this approach? Is it right to use many methods there, or is it better to use in class component.

**Comment by wuct** [comment]
@Dictory One small tip to improve performance is that there is no need to use `onlyUpdateForKeys`  after `connect`, because `connect` already done `pure` by default. Placing `onlyUpdateForKeys` after `connect` would make it check same props twice.

There is nothing to stop you composing many HOCs into one, and if using class components can simplify your code, just use it. About performance, my answer is that don't optimize your code without profiling.

**Comment by Dictory** [comment]
@wuct thanks for your answer. I know about `pure`, but what can i do in order to detect only several keys?

**Comment by JunyuanZheng** [comment]
I have the same question, I am using typescript, so if I split all the HOCs into several different files, how can I chain them together, e.g, make sure it is type safe.

**Comment by wuct** [comment]
@Dictory you can override how `connect()` compare props and state. Please see react-redux [doc](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) for how to do it.

@JunyuanZheng I'm not familiar with TypeScript, but I think you can define the type for each HOC like how we do with Flow in [this file](https://github.com/acdlite/recompose/blob/master/types/flow-typed/recompose_v0.24.x/flow_v0.55.x-/recompose_v0.24.x.js).

**Comment by wuct** [comment]
I'm going to close this issue now because there is not too much we can do here. Please feel free to discuss here or re-open it if you have further thought.
