### ISSUE TITLE
API doc clarification

### ISSUE THREAD

**Issue by joelburget** [acdlite/recompose#6]
> Although it has the same effect, using the defaultProps() HoC is not the same as setting the static defaultProps property directly on the component.

Intriguing, but unsatisfying. I think this statement merits a word on how it's _not_ the same.

**Comment by acdlite** [comment]
Yeah you're right. In fact, this topic should probably be moved to its own section, since it applies to more than just `defaultProps()`.

The basic point is that certain helpers like `defaultProps()` and `shouldUpdate()` have analogues in the React Component API, but since they are higher-order components, they are applied on a container component that wraps the base component, rather than directly on the base component itself. The effect is the same, but the implementation is slightly different.

**Comment by wuct** [comment]
I am going to close this issue because it's no longer active. Please feel free to reopen it and a PR for doc enhancement is always welcome.
