### ISSUE TITLE
withHandlers does not allow calling handlers within other handlers

### ISSUE THREAD

**Issue by vampolo** [acdlite/recompose#607]
Hi,

It seems that I can't reference a handler within another handler in the same withHandler call. Let me show that as an example:

```
compose(
withHandlers({
  select: ({ x }) => () => console.log('selected'),
  selectAndRedirect({ select, history }) => (x) => {
    select(x); //----> select is undefined
    history.push('blabla');
  }
})
);
```

The workaround is to split on different handlers calls like:

```
compose(
withHandlers({
  select: ({ x }) => () => console.log('selected'),
}),
withHandlers({
  selectAndRedirect({ select, history }) => (x) => {
    select(x); //----> select is now available
    history.push('blabla');
  }
}));
```

It would be nice if the extra `withHandler` was not needed

**Comment by wuct** [comment]
Thanks for your thought! We have discussed this in #401, and we decided not to add this feature to Recompose. I'm going to close this issue because it's a duplicate issue. Please comment your thought under #401.

By the way, there might be a mistake in your code. If you want to access `x` in `select`, you should move `x` to the second argument.

```
compose(
withHandlers({
  select: () => (x) => console.log('selected'),
}),
withHandlers({
  selectAndRedirect({ select, history }) => (x) => {
    select(x); //----> select is now available
    history.push('blabla');
  }
}));
```
