### ISSUE TITLE
WithStatehandler

### ISSUE THREAD

**Issue by GollyJer** [acdlite/recompose#608]
_React Native_

With the below code I can compose `DimensionEnhancer` into components and add `measurementToProps` to the onLayout prop of any view.  Then I can access `props.measurement.name.width` _(or height, x, y)_ inside the component.  Right now I only use it to determine the size of a camera component, 'cameraViewport'.

What I want is to call it with a name parameter. Like...
```javascript
<View style={styles.someStyles} onLayout={measurementsToProps('someThing')} />
```
And then access `props.measurements.someThing.width`.

```javascript
const DimensionEnhancer = withStateHandlers(
  {
    measurements: {},
  },
  {
    measurementsToProps: ({ measurements }) => (event, name = undefined) => {
      // TODO: figure out how to pass a name into this function.
      const { nativeEvent: { layout } } = event;
      return {
        measurements: {
          ...measurements,
          [name || 'cameraViewport']: {
            ...layout, // layout: { width, height, x, y }
          },
        },
      };
    },
  },
);
```

Thanks for any help.  I wasn't quite able to follow along at [withStateHandlers does not allow for partially applied functions](https://github.com/acdlite/recompose/issues/558) which seems to have some insight.

Thanks!

**Comment by steve-a-jones** [comment]
You should be able to do this actually.. I have plenty of instances where I partially apply args to these handlers, but you will need to use a partial application utility to achieve this because there is no way for recompose to know that you are implementing partial application.. so you essentially are only able to define a single handler function.

In `<View style={styles.someStyles} onLayout={measurementsToProps('someThing')} />` you are invoking the handler, which is just called like a regular function.

I'm using `partial` from lodash, and with that you could do something like..

`<View style={styles.someStyles} onLayout={partial(measurementsToProps, 'someThing')} />`

but keep in mind that order the arguments are applied in.. you would need to reverse the arguments in your handler to have the event come second as `someThing` will be the first argument applied.

**Comment by wuct** [comment]
As @steve-a-jones said, there is no way for Recompose to know that you are using curried functions.

I'm going to close this issue. Please feel free to reopen it if you have further thought.
