### ISSUE TITLE
"onlyUpdateForKeys" or "pure" with react-router.

### ISSUE THREAD

**Issue by johnunclesam** [acdlite/recompose#618]
I'm sorry, I'm very newbie.

I wrote this: https://codesandbox.io/s/623o62570z to understand.

I use this code in `Home` component:

```javascript
import React from "react";
import { onlyUpdateForKeys } from "recompose";

const Home = () => {
  console.log("Home render!");
  return <div>Home</div>;
};

export default onlyUpdateForKeys([])(Home);
```

and I thought **it would never be rendered**.

Instead from page to page I see in console: `Home render!`

**Where am I wrong?**

**Comment by istarkov** [comment]
First time it would be rendered always. Just not rerendered.
Router renders component from scratch in your example if you switch route.

**Comment by johnunclesam** [comment]
@istarkov, yes. I now understand. But maybe I can use `render`? Like this:

**Comment by johnunclesam** [comment]
So in this case when I switch route it assign my component to Garbage collector? Is it garbage already?

**Comment by johnunclesam** [comment]
Now here https://codesandbox.io/s/4rq3x51490 I'm using `render={()=><Component/>}`.

**But it's the same.** :(

**Comment by istarkov** [comment]
If you don't want to, use children callback and some kind of css display none i.e

```javascript
<Route path={blabla} children={({ match, ...rest }) => (
  <React.Fragment>
       <A display={match} />
       <B display={!match} />
  </React.Fragment>
)}/>
```

**Comment by istarkov** [comment]
I'll close this ;-)

**Comment by johnunclesam** [comment]
So there is no way to re-use component with react-router except css trick?!?

**Comment by istarkov** [comment]
How you will hide component from dom? ;-)
I know other methods like render content above instead of hide, etc ;-)

You can for example set `if (!props.display) return null;` so you component will be reused but it's children are not.
Don't think about reusing, garbage and other stuff - it's so really rare cases in web development so I don't know what are you writing that you think about.
Based on my experience all that performance issues  usually have novice developers in their mind but not in any real example ;-)
