### ISSUE TITLE
Use webpack's side-effects flag to enable tree shaking in Webpack 4

### ISSUE THREAD

**Issue by ConneXNL** [acdlite/recompose#619]
This library is missing the "sideEffects" : false in the package.json to enable Webpack 4 tree shaking.

Lodash-es example:
https://github.com/lodash/lodash/blob/master/package.json#L10

This would be a (better) alternative for:
https://github.com/acdlite/recompose#using-babel-plugin-lodash

**Comment by wuct** [comment]
Thanks for bringing this up!

**Comment by TrySound** [comment]
This is not relevant anymore
https://github.com/acdlite/recompose/blob/master/.size-snapshot.json#L17-L18

**Comment by billyjanitsch** [comment]
@TrySound why is it not relevant anyway? I realize that webpack can already tree-shake this package to some extent (thanks to your work! 😊) but can't adding `sideEffects: false` only help further?

**Comment by billyjanitsch** [comment]
Also, I notice that `.size-snapshot.json` never actually gets updated as e.g. a pre-commit hook, so the [version in master](https://github.com/acdlite/recompose/blob/7a9e2d2d794b0c8cf8772184fcf7621abd551f0e/.size-snapshot.json) corresponds to the snapshot when you made the [initial rollup snapshot commit](https://github.com/acdlite/recompose/commit/a108f64d2d940f058de9579cd45daf8c9b158a64), despite [changes](https://github.com/acdlite/recompose/commit/6d3765add5dea2c927059c241c2b718ac2270d02) that clearly affect bundle size and possibly tree-shaking having landed since then.

What is the mechanism by which you'd expect the snapshot to update? What's the purpose of having it in the repo?

**Comment by TrySound** [comment]
It's usually should be updated by users. But there is also `matchSnapshot` option which will fail in ci.

**Comment by TrySound** [comment]
Done https://github.com/acdlite/recompose/pull/672
