### ISSUE TITLE
Static Class Properties breaks ie8

### ISSUE THREAD

**Issue by joshacheson** [acdlite/recompose#63]
Static Class Properties compile down to use of `Object.defineProperty` which breaks in ie8. I'm happy to do the refactoring work to do things the (unfortunately less pretty) oldschool way.

Let me know if this sounds good - otherwise I'll have to fork :(

**Comment by acdlite** [comment]
Ah, so Babel's loose mode is supposed to account for this, but it looks like since I updated the release script (which builds and publishes the npm package), the `.babelrc` file is no longer enabled, since the script `cd`s into each package directory.

Long term solution will be to upgrade to Babel 6 and compile down to IE8 compatible code; in the meantime, if you want to submit a PR that either 1) rewrites to the old school way or 2) fixes the release script so that the Babel command is run from the root directory, I will accept.

**Comment by acdlite** [comment]
Here's the line where Babel is run https://github.com/acdlite/recompose/blob/master/scripts/release.js#L88

**Comment by joshacheson** [comment]
After looking at Babel's class property transformer it doesn't appear there is any consideration for loose mode: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-class-properties/src/index.js

Because of this I'll be going down route #1 and refactor to basic old school syntax for these static class props

**Comment by joshacheson** [comment]
@acdlite do you want to keep the use of static class properties in tests? Obviously this will have no impact on ie8 compat and it is definitely a little nicer to read

**Comment by acdlite** [comment]
Sure, that's fine

**Comment by acdlite** [comment]
Fixed by https://github.com/acdlite/recompose/pull/69
